package ca.ulaval.glo2004.gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import ca.ulaval.glo2004.domain.Controleur;
import ca.ulaval.glo2004.domain.gestion_afficheurs.Afficheur;
import ca.ulaval.glo2004.domain.gestion_afficheurs.AfficheurMur;
import ca.ulaval.glo2004.services.CaisseOutils;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.util.Objects;

/**
 * @author safae
 */
public class HomePanel extends javax.swing.JFrame {

    /**
     * Creates new form homePanel
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        info_btn = new javax.swing.JButton();
        Jpanel1 = new javax.swing.JPanel();
        logoDisplay = new javax.swing.JLabel();
        Jpanel = new javax.swing.JPanel();
        chaletPreviewDisplay = new javax.swing.JLabel();
        creerNouveauProjet_btn = new javax.swing.JButton();
        ouvrirProjetExistant_btn = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        root.setBackground(new java.awt.Color(64, 65, 73));
        root.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(77, 78, 87));

        info_btn.setBackground(new java.awt.Color(77, 78, 87));
        info_btn.setForeground(new java.awt.Color(255, 255, 255));
        info_btn.setText("Info");
        info_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onInfoBtnClicked(evt);
            }
        });

        logoDisplay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoDisplay.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout Jpanel1Layout = new javax.swing.GroupLayout(Jpanel1);
        Jpanel1.setLayout(Jpanel1Layout);
        Jpanel1Layout.setHorizontalGroup(
            Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );
        Jpanel1Layout.setVerticalGroup(
            Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(info_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(info_btn)
                .addGap(37, 37, 37))
        );

        Jpanel.setMaximumSize(new java.awt.Dimension(610, 415));
        Jpanel.setMinimumSize(new java.awt.Dimension(610, 415));

        chaletPreviewDisplay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chaletPreviewDisplay.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        chaletPreviewDisplay.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 102, 51)));

        javax.swing.GroupLayout JpanelLayout = new javax.swing.GroupLayout(Jpanel);
        Jpanel.setLayout(JpanelLayout);
        JpanelLayout.setHorizontalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chaletPreviewDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        JpanelLayout.setVerticalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chaletPreviewDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        creerNouveauProjet_btn.setBackground(new java.awt.Color(77, 78, 87));
        creerNouveauProjet_btn.setForeground(new java.awt.Color(255, 255, 255));
        creerNouveauProjet_btn.setText("Nouveau");
        creerNouveauProjet_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCreerNouveauProjetClicked(evt);
            }
        });

        ouvrirProjetExistant_btn.setBackground(new java.awt.Color(77, 78, 87));
        ouvrirProjetExistant_btn.setForeground(new java.awt.Color(255, 255, 255));
        ouvrirProjetExistant_btn.setText("Ouvrir");
        ouvrirProjetExistant_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOuvrirProjetExistantClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenue à ChalCLT !");
        jLabel1.setForeground(Color.WHITE);
        jLabel1.setFont(new Font("Segeo UI",Font.PLAIN,40));

        javax.swing.GroupLayout rootLayout = new javax.swing.GroupLayout(root);
        root.setLayout(rootLayout);
        rootLayout.setHorizontalGroup(
            rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(creerNouveauProjet_btn)
                        .addGap(196, 196, 196)
                        .addComponent(ouvrirProjetExistant_btn))
                    .addGroup(rootLayout.createSequentialGroup()
                        .addComponent(Jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );
        rootLayout.setVerticalGroup(
            rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rootLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creerNouveauProjet_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ouvrirProjetExistant_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel;
    private javax.swing.JPanel Jpanel1;
    private javax.swing.JLabel chaletPreviewDisplay;
    private javax.swing.JButton creerNouveauProjet_btn;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton info_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logoDisplay;
    private javax.swing.JButton ouvrirProjetExistant_btn;
    private javax.swing.JPanel root;
    // End of variables declaration//GEN-END:variables

    private Controleur controleur;
    private MainWindow mainWindow;

    public HomePanel() {
        iniView();
        controleur = new Controleur();
    }

    private void iniView() {
        initComponents();
        showImagesEtLogo();
        setResizable(false);
        setTitle("ChalCLT");
//        setLocationRelativeTo(null);
    }

    private void showImagesEtLogo() {
    }

    /**
     * sert à changer de vue lorsqu'on ouvre ou créer un projet
     */
    private void changerVue() {
        this.setVisible(false);
        mainWindow.setVisible(true);
    }

    /**
     * @param evt
     */
    private void onInfoBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onInfoBtnClicked
    }//GEN-LAST:event_onInfoBtnClicked

    /**
     * @param evt
     */
    public void onOuvrirProjetExistantClicked(ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        int choix = fileChooser.showOpenDialog(null);

        if (choix == JFileChooser.APPROVE_OPTION) {
            File fichierChoisi = fileChooser.getSelectedFile();
            String cheminFichier = fichierChoisi.getAbsolutePath();

            this.controleur.charger(cheminFichier);

            // Stockez le chemin du fichier actuellement ouvert dans votre MainWindow
            mainWindow = new MainWindow(controleur);
            mainWindow.setCheminFichierActuel(cheminFichier);
            changerVue();
        }
    }

    /**
     * @param evt
     */
    public void onCreerNouveauProjetClicked(ActionEvent evt) {
        this.controleur.nouveauProjet();
        mainWindow = new MainWindow(controleur);
        changerVue();
    }


}
