/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ca.ulaval.glo2004.gui;

import ca.ulaval.glo2004.domain.Controleur;
import ca.ulaval.glo2004.domain.gestion_chalet.Accessoire;
import ca.ulaval.glo2004.domain.gestion_chalet.Mur;
import ca.ulaval.glo2004.domain.gestion_chalet.accessoires.Fenetre;
import ca.ulaval.glo2004.services.UniteImperiale;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import javax.swing.TransferHandler;
/**
 * @author nasmachaoui
 */
public class MurDetailsPanel extends javax.swing.JPanel {


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LongueurLabel = new javax.swing.JLabel();
        longueurTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        LargeurLabel = new javax.swing.JLabel();
        largeurTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        epaisseurTextField = new javax.swing.JTextField();
        EpaisseurLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        redimensionerMur = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        espacementAccessoireTextField = new javax.swing.JTextField();
        EpaisseurLabel1 = new javax.swing.JLabel();

        LongueurLabel.setText("Longueur");

        longueurTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        longueurTextField.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LongueurLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(longueurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(14, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LongueurLabel)
                                        .addComponent(longueurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
        );

        LargeurLabel.setText("Largeur");

        largeurTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        largeurTextField.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LargeurLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(largeurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LargeurLabel)
                                        .addComponent(largeurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(10, Short.MAX_VALUE))
        );

        epaisseurTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        epaisseurTextField.setPreferredSize(new java.awt.Dimension(100, 30));

        EpaisseurLabel.setText("Épaisseur ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(EpaisseurLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(epaisseurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(epaisseurTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EpaisseurLabel))
                                .addContainerGap())
        );

        redimensionerMur.setText("Modifier les murs");
        redimensionerMur.setMaximumSize(new java.awt.Dimension(100, 35));
        redimensionerMur.setMinimumSize(new java.awt.Dimension(100, 35));
        redimensionerMur.setPreferredSize(new java.awt.Dimension(100, 35));
        redimensionerMur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redimensionerMurActionPerformed(evt);
                mainWindow.refresh();
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(redimensionerMur, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(redimensionerMur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel5.setToolTipText("Espacement entre les accessoires");

        espacementAccessoireTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        espacementAccessoireTextField.setPreferredSize(new java.awt.Dimension(100, 30));

        EpaisseurLabel1.setText("Espacement");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(EpaisseurLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(espacementAccessoireTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(espacementAccessoireTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EpaisseurLabel1))
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(17, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void redimensionerMurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redimensionerMurActionPerformed
        String longueurMurText = longueurTextField.getText();
        String largeurMurText = largeurTextField.getText();
        String epaisseurMurText = epaisseurTextField.getText();
        String espacementAccesoireText = espacementAccessoireTextField.getText();
        controleur.modifierMur(mainWindow.getDrawingPanelSize(),
                new UniteImperiale(largeurMurText),
                new UniteImperiale(longueurMurText),
                new UniteImperiale(epaisseurMurText),
                new UniteImperiale(espacementAccesoireText));
        remplirAffichageDetails(controleur.getMurSelectionnne()); // TODO bug lorsqu'on est sur la vue dessus
        mainWindow.setvueMode(mainWindow.getvueMode());
        mainWindow.refresh();
    }//GEN-LAST:event_redimensionerMurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EpaisseurLabel;
    private javax.swing.JLabel EpaisseurLabel1;
    private javax.swing.JLabel LargeurLabel;
    private javax.swing.JLabel LongueurLabel;
    private javax.swing.JTextField epaisseurTextField;
    private javax.swing.JTextField espacementAccessoireTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField largeurTextField;
    private javax.swing.JTextField longueurTextField;
    private javax.swing.JButton redimensionerMur;
    // End of variables declaration//GEN-END:variables

    private Controleur controleur;
    private MainWindow mainWindow;

    /**
     * Creates new form MurDetailsPanel
     */
    public MurDetailsPanel(MainWindow p_mainWindow, Controleur p_controleur) {
        controleur = p_controleur;
        mainWindow = p_mainWindow;
        initComponents();
        preparerTextFields();
    }
    private void preparerTextFields() {
        DocumentListener textFieldListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateButtonState();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateButtonState();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateButtonState();
            }

        };
        longueurTextField.getDocument().addDocumentListener(textFieldListener);
        largeurTextField.getDocument().addDocumentListener(textFieldListener);
        epaisseurTextField.getDocument().addDocumentListener(textFieldListener);
        espacementAccessoireTextField.getDocument().addDocumentListener(textFieldListener);
    }

    protected void viderToutVueDetails() {
        epaisseurTextField.setText("");
        largeurTextField.setText("");
        longueurTextField.setText("");
        espacementAccessoireTextField.setText("");
    }

    protected void remplirAffichageDetails(Mur p_mur) {
        largeurTextField.setText(p_mur.getLargeur() + "");
        longueurTextField.setText(p_mur.getLongueur() + "");
        epaisseurTextField.setText(p_mur.getEpaisseur() + "");
        espacementAccessoireTextField.setText(p_mur.getEspacementAccessoires() + "");
    }

    private void updateButtonState() {
        // Récupérez les valeurs à partir des champs de texte
        String longueurMurText = longueurTextField.getText();
        String largeurMurText = largeurTextField.getText();
        String epaisseurtText = epaisseurTextField.getText();
        String espacementText = espacementAccessoireTextField.getText();


        // S'assure de valider et de convertir ces valeurs en types numériques ( pour livrable 3)
        if (longueurMurText != null && largeurMurText != null && epaisseurtText != null && espacementText != null) {
            boolean estVide = longueurMurText.isEmpty() || largeurMurText.isEmpty() || epaisseurtText.isEmpty() || espacementText.isEmpty();
            boolean match = longueurMurText.matches(UniteImperiale.FORMAT_UNITE_IMPERIAL.pattern())
                    && largeurMurText.matches(UniteImperiale.FORMAT_UNITE_IMPERIAL.pattern())
                    && epaisseurtText.matches(UniteImperiale.FORMAT_UNITE_IMPERIAL.pattern())
                    && espacementText.matches(UniteImperiale.FORMAT_UNITE_IMPERIAL.pattern());
            boolean doesNotEndWithBackSlash = !(longueurMurText.endsWith("/") || largeurMurText.endsWith("/") || epaisseurtText.endsWith("/") || espacementText.endsWith("/"));


            if (!estVide && match && doesNotEndWithBackSlash) {
                UniteImperiale longueurMur = new UniteImperiale(longueurMurText);
                UniteImperiale largeurMur = new UniteImperiale(largeurMurText);
                UniteImperiale epaisseurMur = new UniteImperiale(epaisseurtText);
                UniteImperiale espacementMur = new UniteImperiale(espacementText);

                if (longueurMur.estValide() && largeurMur.estValide() && epaisseurMur.estValide() && espacementMur.estValide()) {
                    // Active le boutton "Redimensionner le mur" si les deux sont valides
                    redimensionerMur.setEnabled(true);
                }
            } else {
                redimensionerMur.setEnabled(false);
            }
        }
    }

}
