/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ca.ulaval.glo2004.gui;

import ca.ulaval.glo2004.domain.Controleur;
import ca.ulaval.glo2004.domain.gestion_chalet.Accessoire;
import ca.ulaval.glo2004.domain.gestion_chalet.accessoires.Porte;
import ca.ulaval.glo2004.domain.gestion_chalet.Mur;
import ca.ulaval.glo2004.gui.util.TypeVueDetails;
import ca.ulaval.glo2004.services.CaisseOutils;
import ca.ulaval.glo2004.services.Orientations;
import ca.ulaval.glo2004.services.UniteImperiale;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 * @author nasmachaoui
 */
public class PorteDetailsPanel extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accesoireValidite_label;
    private javax.swing.JButton creerPorte_btn;
    private javax.swing.JButton deplacer_btn;
    private javax.swing.JTextField emplacementx_textField;
    private javax.swing.JTextField emplacementy_textField;
    private javax.swing.JLabel emplacemntLabelx;
    private javax.swing.JLabel emplacemntLabely;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel largeurLabel;
    private javax.swing.JTextField largeurTextField;
    private javax.swing.JLabel longueurLabel;
    private javax.swing.JTextField longueurTextField;
    private javax.swing.JButton redimensionerPorte_btn;
    private javax.swing.JButton supprimerPorte_btn;
    // End of variables declaration//GEN-END:variables
    private Controleur controleur;
    private MainWindow mainWindow;

    private boolean modeCreation;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        emplacemntLabelx = new javax.swing.JLabel();
        emplacementx_textField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        longueurLabel = new javax.swing.JLabel();
        longueurTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        supprimerPorte_btn = new javax.swing.JButton();
        redimensionerPorte_btn = new javax.swing.JButton();
        deplacer_btn = new javax.swing.JButton();
        creerPorte_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        emplacemntLabely = new javax.swing.JLabel();
        emplacementy_textField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        largeurLabel = new javax.swing.JLabel();
        largeurTextField = new javax.swing.JTextField();
        accesoireValidite_label = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(300, 400));

        emplacemntLabelx.setText("Emplacement x");

        emplacementx_textField.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(emplacemntLabelx, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(emplacementx_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emplacementx_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emplacemntLabelx))
                .addContainerGap())
        );

        longueurLabel.setText("Longueur");

        longueurTextField.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(longueurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(longueurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(longueurLabel)
                    .addComponent(longueurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        supprimerPorte_btn.setText("Supprimer la porte");
        supprimerPorte_btn.setMaximumSize(new java.awt.Dimension(100, 35));
        supprimerPorte_btn.setMinimumSize(new java.awt.Dimension(100, 35));
        supprimerPorte_btn.setPreferredSize(new java.awt.Dimension(100, 35));
        supprimerPorte_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerPorte_btnActionPerformed(evt);
            }
        });

        redimensionerPorte_btn.setText("Redimensioner Porte");
        redimensionerPorte_btn.setMaximumSize(new java.awt.Dimension(100, 35));
        redimensionerPorte_btn.setMinimumSize(new java.awt.Dimension(100, 35));
        redimensionerPorte_btn.setPreferredSize(new java.awt.Dimension(100, 35));
        redimensionerPorte_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redimensionerPorte_btnActionPerformed(evt);
            }
        });

        deplacer_btn.setText("Déplacer");
        deplacer_btn.setEnabled(false);
        deplacer_btn.setMaximumSize(new java.awt.Dimension(100, 35));
        deplacer_btn.setMinimumSize(new java.awt.Dimension(100, 35));
        deplacer_btn.setPreferredSize(new java.awt.Dimension(100, 35));
        deplacer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deplacer_btnActionPerformed(evt);
            }
        });

        creerPorte_btn.setText("Créer la porte");
        creerPorte_btn.setMaximumSize(new java.awt.Dimension(100, 35));
        creerPorte_btn.setMinimumSize(new java.awt.Dimension(100, 35));
        creerPorte_btn.setPreferredSize(new java.awt.Dimension(100, 35));
        creerPorte_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerPorte_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redimensionerPorte_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(supprimerPorte_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deplacer_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(creerPorte_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(creerPorte_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(deplacer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(redimensionerPorte_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(supprimerPorte_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        emplacemntLabely.setText("Emplacement y");

        emplacementy_textField.setEditable(false);
        emplacementy_textField.setToolTipText("");
        emplacementy_textField.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(emplacemntLabely, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(emplacementy_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emplacemntLabely)
                    .addComponent(emplacementy_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        largeurLabel.setText("Largeur");

        largeurTextField.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(largeurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(largeurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(largeurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(largeurLabel)))
        );

        accesoireValidite_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accesoireValidite_label.setMaximumSize(new java.awt.Dimension(150, 25));
        accesoireValidite_label.setMinimumSize(new java.awt.Dimension(150, 25));
        accesoireValidite_label.setName(""); // NOI18N
        accesoireValidite_label.setPreferredSize(new java.awt.Dimension(150, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(accesoireValidite_label, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(accesoireValidite_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Creates new form PorteDetailsPanel
     *
     * @param p_mainWindow
     * @param p_controleur
     */
    public PorteDetailsPanel(MainWindow p_mainWindow, Controleur p_controleur) {
        mainWindow = p_mainWindow;
        controleur = p_controleur;
        modeCreation = false;
        initComponents();
        setName(TypeVueDetails.PORTE.type);
        preparerTextFields();

    }

    private void preparerTextFields() {
        DocumentListener textFieldListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateButtonState();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateButtonState();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateButtonState();
            }
        };
        longueurTextField.getDocument().addDocumentListener(textFieldListener);
        largeurTextField.getDocument().addDocumentListener(textFieldListener);
        emplacementx_textField.getDocument().addDocumentListener(textFieldListener);
    }


    protected void viderToutVueDetails() {
        emplacementx_textField.setText("");
        emplacementy_textField.setText("");
        largeurTextField.setText("");
        longueurTextField.setText("");
        creerPorte_btn.setEnabled(false);
        redimensionerPorte_btn.setEnabled(false);
        deplacer_btn.setEnabled(false);
        supprimerPorte_btn.setEnabled(false);
    }

    protected void remplirAffichageDetails(Porte p_porte) {
        emplacementx_textField.setText(p_porte.getCoordonneesEmplacement()[0] + "");
        emplacementy_textField.setText(p_porte.getCoordonneesEmplacement()[1] + "");
        largeurTextField.setText(p_porte.getLargeur() + "");
        longueurTextField.setText(p_porte.getLongueur() + "");
        creerPorte_btn.setEnabled(false);
        redimensionerPorte_btn.setEnabled(true);
        deplacer_btn.setEnabled(true);
        supprimerPorte_btn.setEnabled(true);
        accesoireValidite_label.setText("Accessoire " + (p_porte.estValide() ? "valide" : "invalide"));
    }

    private void updateButtonState() {
        // Récupérez les valeurs à partir des champs de texte
        String longueurPorteText = longueurTextField.getText();
        String largeurPorteText = largeurTextField.getText();
        String posPorteXText = emplacementx_textField.getText();

        // S'assure de valider et de convertir ces valeurs en types numériques ( pour livrable 3)
        if (longueurPorteText != null && largeurPorteText != null && posPorteXText != null) {
            boolean estVide = longueurPorteText.isEmpty() || largeurPorteText.isEmpty() || posPorteXText.isEmpty();
            boolean match = longueurPorteText.matches(UniteImperiale.FORMAT_UNITE_IMPERIAL.pattern())
                    && largeurPorteText.matches(UniteImperiale.FORMAT_UNITE_IMPERIAL.pattern())
                    && posPorteXText.matches(UniteImperiale.FORMAT_UNITE_IMPERIAL.pattern());
            boolean doesNotEndWithBackSlash = !(longueurPorteText.endsWith("/") || largeurPorteText.endsWith("/") || posPorteXText.endsWith("/"));

            if (!estVide && match && doesNotEndWithBackSlash) {
                UniteImperiale longueurPorte = new UniteImperiale(longueurPorteText);
                UniteImperiale largeurPorte = new UniteImperiale(largeurPorteText);
                UniteImperiale posPorteX = new UniteImperiale(posPorteXText);

                boolean valeursValide = longueurPorte.estValide() && largeurPorte.estValide() && posPorteX.estValide();

                if (valeursValide && modeCreation) {
                    // Active le boutton "Créer la porte" si les deux sont valides
                    creerPorte_btn.setEnabled(true);
                } else if (valeursValide && !modeCreation) {
                    redimensionerPorte_btn.setEnabled(true);
                    deplacer_btn.setEnabled(true);
                    supprimerPorte_btn.setEnabled(true);
                }
                for (Mur mur : controleur.getComposantes()) {
                    for (Accessoire pAcc : mur.getAccessoiresListes()) {
                        if (pAcc.estSelectionne() && pAcc instanceof Porte) {
                            creerPorte_btn.setEnabled(false);
                        }
                    }
                }
            } else {
                creerPorte_btn.setEnabled(false);
                redimensionerPorte_btn.setEnabled(false);
                deplacer_btn.setEnabled(false);
                supprimerPorte_btn.setEnabled(false);
            }
        }
    }

    protected void creationMode(boolean p_estEnModeCreation) {
        modeCreation = p_estEnModeCreation;
    }

    private void creerPorte_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerPorte_btnActionPerformed
        // Récupérez les valeurs de longueur et de largeur à partir des champs de texte
        String longueurPorteText = longueurTextField.getText();
        String largeurPorteText = largeurTextField.getText();
        Orientations orientation = mainWindow.getvueMode();

        //Récupérer l'emplacement en x et automatiquement l'emplcement en y est calculer puisqu'une porte est toujours coller au bas du mur
        String emplacementPortex = emplacementx_textField.getText();

        // Enregistrez la porte avec le controleur
        controleur.creationPorte(new UniteImperiale(largeurPorteText), new UniteImperiale(longueurPorteText), new UniteImperiale(emplacementPortex), orientation);

        // Réinitialisez les champs de texte
        viderToutVueDetails();

        //redessine Mur
        mainWindow.setvueMode(mainWindow.getvueMode());
        mainWindow.refresh();
    }//GEN-LAST:event_creerPorte_btnActionPerformed

    private void supprimerPorte_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerPorte_btnActionPerformed
        // Action exécutée lors de la suppression d'une fenêtre
        boolean noAccessoires = false;
        for (Mur mur : controleur.getComposantes()) {
            if (mur.getCote() == mainWindow.getvueMode()) {
                if (mur.getNbrAccessoire() == 0) {
                    noAccessoires = true;
                    JDialog popup = new JDialog(mainWindow, "Erreur", true);
                    popup.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    String text = "Le mur ne contient pas de portes pour supprimer";
                    // Create a label in the popup
                    JLabel label = new JLabel(text);
                    popup.setSize(text.length() * 9, 100);
                    label.setHorizontalAlignment(SwingConstants.CENTER);
                    popup.add(label);

                    // Center the popup window on the screen
                    popup.setLocationRelativeTo(null);

                    // Make the popup window visible
                    popup.setVisible(true);
                }
            }
        }
        boolean selectionnee = false;

        // Parcourt tous les éléments du contrôleur pour trouver les accessoires sélectionnés qui sont des fenêtres
        for (Mur mur : controleur.getComposantes()) {
            for (Accessoire pAcc : mur.getAccessoiresListes()) {
                if (pAcc.estSelectionne() && pAcc instanceof Porte) {
                    Orientations o = mainWindow.getvueMode();
                    selectionnee = true;
                    controleur.supprimerAccessoire(pAcc.getCoordonneesEmplacement(), o);
                    viderToutVueDetails();
                    mainWindow.detailsPanelVide();
                    mainWindow.setvueMode(o); // Met à jour l'orientation dans la fenêtre principale
                }
            }
        }


        if (!selectionnee && !noAccessoires) {
            JDialog popup = new JDialog(mainWindow, "Erreur", true);
            popup.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            String text = "Choisis la porte a supprimer";
            // Create a label in the popup
            JLabel label = new JLabel(text);
            popup.setSize(text.length() * 9, 100);
            label.setHorizontalAlignment(SwingConstants.CENTER);
            popup.add(label);

            // Center the popup window on the screen
            popup.setLocationRelativeTo(null);

            // Make the popup window visible
            popup.setVisible(true);
        }
        mainWindow.refresh();
    }//GEN-LAST:event_supprimerPorte_btnActionPerformed

    private void deplacer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deplacer_btnActionPerformed
        // TODO add your handling code here:
        UniteImperiale[] coordonneesEmplacementNouveau = {new UniteImperiale(emplacementx_textField.getText()), null};
        for (Mur auto_element : controleur.getComposantes()) {
            for (Accessoire pAcc : auto_element.getAccessoiresListes()) {
                if (pAcc.estSelectionne()) //on trouve l'accesoire selectionne
                {
                    controleur.updateCoordonnees(pAcc, coordonneesEmplacementNouveau, CaisseOutils.RATIO_TEST);
                    //orientations mur
                    remplirAffichageDetails((Porte) pAcc);
                    mainWindow.setvueMode(mainWindow.getvueMode());
                    if (pAcc.estSelectionne() && !(emplacementx_textField.getText()).isEmpty()) {
                        // Active le boutton "Créer la porte" si les deux sont valides
                        deplacer_btn.setEnabled(true);
                    }
                }
            }
        }
        mainWindow.refresh();
    }//GEN-LAST:event_deplacer_btnActionPerformed

    private void redimensionerPorte_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redimensionerPorte_btnActionPerformed
        // TODO add your handling code here:
        // Récupérez les valeurs de longueur et de largeur à partir des champs de texte
        String longueurPorteText = longueurTextField.getText();
        String largeurPorteText = largeurTextField.getText();


        for (Mur auto_element : controleur.getComposantes()) {
            for (Accessoire pAcc : auto_element.getAccessoiresListes()) {
                if (pAcc.estSelectionne()) //on trouve l'accesoire selectionne
                {
                    //TODO revoir parce que ça marche pas
                    controleur.updateAccessoireDimension(pAcc, new UniteImperiale(largeurPorteText), new UniteImperiale(longueurPorteText));
                    remplirAffichageDetails((Porte) pAcc);
                    //orientations mur
                    mainWindow.setvueMode(mainWindow.getvueMode());
                    if (pAcc.estSelectionne() && !(longueurPorteText.isEmpty())) {
                        // Active le boutton "Déplacer" si les deux sont valides
                        redimensionerPorte_btn.setEnabled(true);
                    }
                }
            }
        }
        mainWindow.refresh();
    }//GEN-LAST:event_redimensionerPorte_btnActionPerformed
}

