/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ca.ulaval.glo2004.gui;

import ca.ulaval.glo2004.domain.Controleur;
import ca.ulaval.glo2004.gui.util.ButtonGroupPersonnalise;
import ca.ulaval.glo2004.services.ExportationMode;

import javax.swing.*;
import javax.swing.filechooser.FileSystemView;
import java.awt.event.ActionListener;

/**
 * @author safae
 */
public class STLExportationPanel extends javax.swing.JPanel {


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        brut_radioBtn = new javax.swing.JRadioButton();
        fini_radioBtn = new javax.swing.JRadioButton();
        retrait_radioBtn = new javax.swing.JRadioButton();
        exporter_btn = new javax.swing.JButton();

        brut_radioBtn.setText("Brut");
        brut_radioBtn.setMaximumSize(new java.awt.Dimension(100, 50));
        brut_radioBtn.setMinimumSize(new java.awt.Dimension(100, 50));
        brut_radioBtn.setPreferredSize(new java.awt.Dimension(100, 50));

        fini_radioBtn.setText("Fini");
        fini_radioBtn.setMaximumSize(new java.awt.Dimension(100, 50));
        fini_radioBtn.setMinimumSize(new java.awt.Dimension(100, 50));
        fini_radioBtn.setPreferredSize(new java.awt.Dimension(100, 50));

        retrait_radioBtn.setText("Retrait");
        retrait_radioBtn.setMaximumSize(new java.awt.Dimension(100, 50));
        retrait_radioBtn.setMinimumSize(new java.awt.Dimension(100, 50));
        retrait_radioBtn.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(retrait_radioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fini_radioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brut_radioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brut_radioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fini_radioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retrait_radioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        exporter_btn.setText("Exporter");
        exporter_btn.setMaximumSize(new java.awt.Dimension(150, 50));
        exporter_btn.setMinimumSize(new java.awt.Dimension(150, 50));
        exporter_btn.setPreferredSize(new java.awt.Dimension(150, 50));
        exporter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onExportationClick(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exporter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(exporter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton brut_radioBtn;
    private javax.swing.JButton exporter_btn;
    private javax.swing.JRadioButton fini_radioBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton retrait_radioBtn;
    // End of variables declaration//GEN-END:variables
    private ButtonGroupPersonnalise exportationMode_btnGroup;
    private MainWindow mainWindow;
    private Controleur controleur;
    private ExportationMode exportationMode;

    /**
     * Creates new form STL
     */
    public STLExportationPanel(MainWindow p_mainWindow, Controleur p_controleur) {
        initComponents();
        mainWindow = p_mainWindow;
        controleur = p_controleur;
        exportationMode_btnGroup = new ButtonGroupPersonnalise();
        preparerButtons();
    }

    public void preparerButtons() {
        /*preparation du changement de mode d'exportation */
        ActionListener changementModeListener = e -> {
            if (e.getSource() == fini_radioBtn)
                exportationMode = ExportationMode.FINI;
            else if (e.getSource() == retrait_radioBtn)
                exportationMode = ExportationMode.RETRAIT;
            else if (e.getSource() == brut_radioBtn)
                exportationMode = ExportationMode.BRUT;
        };
        fini_radioBtn.addActionListener(changementModeListener);
        retrait_radioBtn.addActionListener(changementModeListener);
        brut_radioBtn.addActionListener(changementModeListener);


        /*preparation des radio button */
        exportationMode_btnGroup.add(fini_radioBtn);
        exportationMode_btnGroup.add(retrait_radioBtn);
        exportationMode_btnGroup.add(brut_radioBtn);
        // le mode fini est le mode par defaut d'exportation
        fini_radioBtn.setSelected(true);
        exportationMode = ExportationMode.FINI;
    }

    private void onExportationClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onExportationClick
        if (!controleur.contientAccessoiresInvalide()) {
            JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int result = fileChooser.showSaveDialog(null);

            if (result == JFileChooser.APPROVE_OPTION) {
                String dossierDestination = fileChooser.getSelectedFile().getPath();
                controleur.exporter(exportationMode, dossierDestination);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Oops! il y'a encore des accessoires invalides...", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_onExportationClick

}
